# Generated by Django 5.2.6 on 2025-10-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ غیرفعال شدن')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('giga', models.PositiveIntegerField(verbose_name='گیگ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('referrer', models.CharField(blank=True, max_length=100, verbose_name='معرف')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='اسم بانک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_at'],
            },
        ),
    ]
