# Generated by Django 5.2.6 on 2025-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید (میلادی)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت (شمسی)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='شماره تماس'),
        ),
    ]
