# Generated by Django 5.2.6 on 2025-10-02 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_customer_expire_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator Admin'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date (Gregorian)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='giga',
            field=models.PositiveIntegerField(verbose_name='Giga'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid Status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date (Shamsi)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referrer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referrer'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spending_date', models.DateField(blank=True, null=True, verbose_name='Spending Date (Shamsi)')),
                ('issue', models.CharField(blank=True, max_length=200, verbose_name='Issue')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Amount')),
                ('is_server_cost', models.BooleanField(default=False, verbose_name='Is it a server cost?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator Admin')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-spending_date'],
            },
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField(blank=True, null=True, verbose_name='Deposit Date (Shamsi)')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Depositor Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator Admin')),
            ],
            options={
                'verbose_name': 'Other Income',
                'verbose_name_plural': 'Other Incomes',
                'ordering': ['-deposit_date'],
            },
        ),
    ]
