# Generated by Django 5.2.6 on 2025-10-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='dark', max_length=10),
        ),
    ]
