# Generated by Django 5.2.6 on 2025-10-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date (Gregorian)'),
        ),
    ]
