# Generated by Django 5.2.6 on 2025-10-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_transfer_customer_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
