# Generated by Django 5.2.6 on 2025-10-12 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_subscriptions', to='dashboard.customerprofile', verbose_name='Service Referrer'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_customers', to='dashboard.customerprofile', verbose_name='Introduced by'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.DeleteModel(
            name='Referrer',
        ),
    ]
