# Generated by Django 5.2.6 on 2025-12-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherincome',
            name='destination_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_incomes', to='dashboard.bankaccount', verbose_name='Destination Bank'),
        ),
    ]
