# Generated by Django 5.2.6 on 2025-12-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_otherincome_destination_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='dashboard.bankaccount', verbose_name='Source Bank'),
        ),
    ]
